### ISSUE TITLE
Deprecated instruction updating metada

### ISSUE THREAD

**Issue by zx9r** [AJcodes42/fungible-token-operator#1]
Hi, when running updateMetaData.ts I'm getting an error. It seems that the instruction used is deprecated. What is the non deprecated version that should be used now?

> $ ts-node updateMetaData.ts
> ---STEP 1: Uploading MetaData---
> Arweave URL:  https://arweave.net/Jl2R9M7wM-2RHVVo5BlaGWh4B3dDXn68Y-tk2QGie4k
> ---STEP 2: Creating Transaction---
> ---STEP 3: Executing Transaction---
> /home/solana/fungible-token-operator/node_modules/@solana/web3.js/src/connection.ts:5792
>       throw new SendTransactionError(
>             ^
> SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x4b
>     at Connection.sendEncodedTransaction (/home/solana/fungible-token-operator/node_modules/@solana/web3.js/src/connection.ts:5792:13)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Connection.sendRawTransaction (/home/solana/fungible-token-operator/node_modules/@solana/web3.js/src/connection.ts:5751:20)
>     at async Connection.sendTransaction (/home/solana/fungible-token-operator/node_modules/@solana/web3.js/src/connection.ts:5739:12) {
>   logs: [
>     'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]',
>     'Program log: This instruction was deprecated in a previous release and is now removed',
>     'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 3615 of 200000 compute units',
>     'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0x4b'
>   ]
> }
>

**Comment by zx9r** [comment]
It seems that the problem is that `createCreateMetadataAccountV2Instruction` is obsolete/deprecated and now `createCreateMetadataAccountV3Instruction` should be used instead
